# .github/workflows/ci-cd.yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-push:
    name: Build, Test & Push Docker Images
    runs-on: ubuntu-latest

    # *** Add this section to link the job to your environment ***
    environment:
      name: ci-cd
      # url: <Optional: URL if this environment deploys somewhere specific>

    permissions:
      contents: read
      packages: write # Still needed if pushing to Docker Hub/GHCR

    steps:
      # 1. Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js and pnpm (Steps remain the same)
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.7.0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      # 3. Install Dependencies (Step remains the same)
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Run Lint Check (Step remains the same)
      - name: Run lint check
        run: pnpm lint

      # 5. Run Build (Step remains the same)
      - name: Run build
        run: pnpm build

      # --- Docker Steps - Now potentially controlled by 'cicd' environment rules ---
      # These steps will now use secrets/variables from the 'cicd' environment first,
      # then fall back to repository secrets/variables if not found in the environment.

      # 6. Set up Docker Buildx
      - name: Set up Docker Buildx
        # Conditional execution remains the same
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/setup-buildx-action@v3

      # 7. Log in to Docker Hub
      - name: Log in to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          # These will now read from 'cicd' environment secrets if they exist there
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 8. Extract Docker metadata for server image (Step remains the same)
      - name: Extract metadata for server image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: meta_server
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fin-cast-server # Ensure DOCKERHUB_USERNAME is available either in repo or cicd env secrets
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      # 9. Build and push server image (Step remains the same)
      - name: Build and push server image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./apps/server/Dockerfile
          push: true
          tags: ${{ steps.meta_server.outputs.tags }}
          labels: ${{ steps.meta_server.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 10. Extract Docker metadata for web image (Step remains the same)
      - name: Extract metadata for web image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: meta_web
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/fin-cast-web # Ensure DOCKERHUB_USERNAME is available
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      # 11. Build and push web image
      - name: Build and push web image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./apps/web/Dockerfile
          push: true
          tags: ${{ steps.meta_web.outputs.tags }}
          labels: ${{ steps.meta_web.outputs.labels }}
          build-args: |
            # This will now read from the 'cicd' environment variable if it exists there
            # Ensure you created PUBLIC_SERVER_URL as a VARIABLE (not secret) in the environment
            PUBLIC_SERVER_URL=${{ vars.PUBLIC_SERVER_URL || 'http://fallback.example.com' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max